icgc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url('^admin/', admin.site.urls),
    url('', include('newwine.urls')),
    url('^tinymce/', include('tinymce.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newwine/urls.py
from django.conf.urls import url
from . import views

app_name = 'newwine'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url('^about/$', views.AboutView.as_view(), name='about'),
    url(r'^executives/$', views.ExecutiveView.as_view(), name='executives'),
    url(r'^department/$', views.DepartmentView.as_view(), name='department'),
    url(r'^documents/$', views.DocumentsView.as_view(), name='documents'),
    url(r'^images/$', views.ImagesView.as_view(), name='images'),
    url(r'^sermons/$', views.SermonsView.as_view(), name='sermons'),
    url(r'^videos/$', views.VideosView.as_view(), name='videos'),
    url(r'^registration/$', views.RegistrationFormView.as_view(), name='registration'),
    url(r'^export/csv/$', views.export_users_csv, name='export_users_csv'),
    url(r'^department/(?P<pk>[0-9]+)/$', views.DepartmentView.as_view(), name='detail'),
    url(r'^theme/$', views.ThemeListView.as_view(), name='theme'),
    url(r'^gender-coordinators/$', views.GenderListView.as_view(), name='gender'),
    url(r'^articles/$', views.ArticlesListView.as_view(), name='articles'),
    url(r'^articles/(?P<pk>[0-9]+)/$', views.ArticlesDetailView.as_view(), name='article-details'),
    url(r'^testimonies/$', views.TestimonyListView.as_view(), name='testimonies'),
    url(r'^testimonies/(?P<pk>[0-9]+)/$', views.TestimonyDetailView.as_view(), name='testimony-details'),
    url(r'^teachings/$', views.NoteListView.as_view(), name='teachings'),
    url(r'^teachings/(?P<pk>[0-9]+)/$', views.NoteDetailView.as_view(), name='teaching-details'),
    url(r'^bible-study-outlines/$', views.OutlineListView.as_view(), name='outlines'),
    url(r'^bible-study-outlines/(?P<pk>[0-9]+)/$', views.OutlineDetailView.as_view(), name='outline-details'),
    url(r'^team/(?P<pk>[0-9]+)/$', views.TeamsListView.as_view(), name='team-detail'),
    url(r'^coordinator/(?P<pk>[0-9]+)/$', views.CoordinatorListView.as_view(), name='coordinator')
]

newwine/models.py
from django.db import models
from tinymce import HTMLField


# Index
class Carousel(models.Model):
    image = models.FileField('File', upload_to='carousel/')
    caption = models.TextField(max_length=300)
    added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Carousel'
        verbose_name_plural = 'Carousel'

    def __str__(self):
        return self.caption


class MainEvent(models.Model):
    image = models.FileField('File', upload_to='event/')
    name = models.CharField(max_length=100)
    details = models.TextField(max_length=500)
    added = models.DateTimeField(auto_now_add=True)
    event_time = models.CharField(max_length=150, default="January 01 1999 00:00:00")

    class Meta:
        verbose_name = 'Main Event'
        verbose_name_plural = 'Main Event'

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField(max_length=300)
    author = models.CharField(max_length=100)
    added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Quote'
        verbose_name_plural = 'Quotes'

    def __str__(self):
        return self.author + " - " + self.quote


class LatestSermons(models.Model):
    added = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100)
    summary = HTMLField('Sermon summary')
    #   summary = models.TextField(max_length=500)

    class Meta:
        verbose_name = 'Latest Sermon'
        verbose_name_plural = 'Latest Sermons'

    def __str__(self):
        return self.title


class Announcements(models.Model):
    added = models.DateTimeField(auto_now_add=True)
    title = models.TextField(default='None')
    announcement = models.TextField(max_length=1000)

    class Meta:
        verbose_name = 'Announcements'
        verbose_name_plural = 'Announcements'

    def __str__(self):
        return self.title

# Index END


# ABOUT

# ABOUT END


# EXECUTIVES
class ExecutivesThumbnail(models.Model):
    profile = models.FileField('File', upload_to='excom/')
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Executives Thumbnails'
        verbose_name_plural = 'Executives Thumbnails'

    def __str__(self):
        return self.name + " - " + self.position


class ExecutivesDetails(models.Model):
    executive = models.ForeignKey(ExecutivesThumbnail, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    hostel = models.CharField(max_length=100)
    course = models.CharField(max_length=150)
    contact = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Executives Details'
        verbose_name_plural = 'Executives Details'

    def __str__(self):
        return self.name + " - " + self.position
# EXECUTIVES END


# IMAGES 2
class Gallery(models.Model):
    class Meta:
        verbose_name = 'Gallery'
        verbose_name_plural = 'Galleries'

    added = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=150)
    album_pic = models.FileField('File', upload_to='album_thumbnails')
    caption = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Images(models.Model):
    file = models.FileField('File', upload_to='gallery_images/')
    gallery = models.ForeignKey(Gallery, blank=True, null=True, on_delete='CASCADE')

    def __str__(self):
        return self.filename

    class Meta:
        verbose_name = 'Image'
        verbose_name_plural = 'Images'

    @property
    def filename(self):
        return self.file.name.rsplit('/', 1)[-1]

# 'File', upload_to='images/'
#   IMAGES 2 END


class RegisteredMembers(models.Model):
    first_name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    email = models.EmailField()
    gender = models.CharField(max_length=20)
    date_of_birth = models.CharField(max_length=50)
    course = models.CharField(max_length=150)
    year = models.CharField(max_length=10)
    hall_or_hostel = models.CharField(max_length=100)
    room = models.CharField(max_length=10)
    department = models.CharField(max_length=70)
    covenant_family = models.CharField(max_length=100)
    home_temple = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Registered Members'
        verbose_name_plural = 'Registered Members'

    def __str__(self):
        return self.first_name + " " + self.surname + " - " + self.phone


#   DEPARTMENTS


class Departments(models.Model):
    department_image = models.FileField('File', upload_to='department_image/')
    department_name = models.CharField(max_length=100)
    department_about = models.TextField(max_length=1000)
    department_function = models.TextField(max_length=1000)
    department_meeting_day_1 = models.CharField(max_length=50)
    department_meeting_day_2 = models.CharField(max_length=50)
    department_meeting_time_1 = models.CharField(max_length=50)
    department_meeting_time_2 = models.CharField(max_length=50)
    department_venue_1 = models.CharField(max_length=50)
    department_venue_2 = models.CharField(max_length=50)
    department_leader_image = models.FileField('File', upload_to='leaders/')
    department_leader_name = models.CharField(max_length=150)
    department_leader_hostel = models.CharField(max_length=100)
    department_leader_course = models.CharField(max_length=150, null=True)
    department_leader_contact = models.CharField(max_length=100)
    department_deputy_image = models.FileField('File', upload_to='leaders/')
    department_deputy_name = models.CharField(max_length=150)
    department_deputy_hostel = models.CharField(max_length=100)
    department_deputy_course = models.CharField(max_length=150, null=True)
    department_deputy_contact = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Department'
        verbose_name_plural = 'Departments'

    def __str__(self):
        return self.department_name

#   DEPARTMENTS END

#   SERMONS


class Sermons(models.Model):
    image = models.FileField('File', upload_to='sermons/')
    audio = models.FileField('File', upload_to='sermons/')
    title = models.CharField(max_length=100)
    minister = models.CharField(max_length=150)
    day_of_message = models.CharField(max_length=50)
    is_playing = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Sermon'
        verbose_name_plural = 'Sermons'

    def __str__(self):
        return self.minister + " - " + self.title
#   SERMONS END


#   COVENANT FAMILY

class Family(models.Model):
    cov_img = models.FileField('File', upload_to='covenant_family/')
    cov_name = models.CharField(max_length=150)
    cov_day = models.CharField(max_length=20)
    cov_time = models.CharField(max_length=10)
    cov_location = models.CharField(max_length=60)
    cov_head = models.CharField(max_length=200)
    cov_head_image = models.FileField('File', upload_to='leaders/')
    cov_course = models.CharField(max_length=150, null=True)
    cov_hostel = models.CharField(max_length=150, null=True)
    cov_contact = models.CharField(max_length=100)
    dept_cov_head = models.CharField(max_length=200)
    dept_head_image = models.FileField('File', upload_to='leaders/')
    dept_cov_course = models.CharField(max_length=150, null=True)
    dept_cov_hostel = models.CharField(max_length=150, null=True)
    dept_cov_head_contact = models.CharField(max_length=150)

    class Meta:
        verbose_name = 'Covenant Family'
        verbose_name_plural = 'Covenant Families'

    def __str__(self):
        return self.cov_name

#   COVENANT FAMILY END

#   INITIATORS


class Initiators(models.Model):
    initiators_img = models.FileField('File', upload_to='initiators_images')
    initiators_name = models.CharField(max_length=200)
    initiators_portfolio = models.CharField(max_length=250)

    class Meta:
        verbose_name = 'Initiator'
        verbose_name_plural = 'Initiators'

    def __str__(self):
        return self.initiators_name

#   INITIATORS END


#   TEAMS

class Teams(models.Model):
    team_name = models.CharField(max_length=300)
    team_role = HTMLField('Team Role')

    class Meta:
        verbose_name = 'Team'
        verbose_name_plural = 'Teams'

    def __str__(self):
        return self.team_name

#   TEAMS END


#   THEME
class Theme(models.Model):
    theme_name = models.CharField(max_length=400, null=True)
    theme_verse_body = HTMLField('Theme Verse Body', null=True)
    theme_verse_scripture = models.CharField(max_length=150, null=True)
    theme_body = HTMLField('Theme Body', null=True)
    theme_tenets = HTMLField('Theme Tenets', null=True)

    class Meta:
        verbose_name = 'Theme'
        verbose_name_plural = 'Themes'

    def __str__(self):
        return self.theme_name

#   THEME END


#   COORDINATOR
class Coordinator(models.Model):
    coord_portfolio = models.CharField(max_length=200)
    coord_img = models.FileField('File', upload_to='coordinators')
    coord_name = models.CharField(max_length=200)
    coord_course = models.CharField(max_length=200)
    coord_hostel = models.CharField(max_length=200)
    coord_contact = models.CharField(max_length=100)
    coord_role = HTMLField('Coordinator Role')

    class Meta:
        verbose_name = 'Coordinator'
        verbose_name_plural = 'Coordinators'

    def __str__(self):
        return self.coord_name+" - "+self.coord_portfolio

#   COORDINATOR END


#   GENDER COORDINATORS
class Gender(models.Model):
    men_coord_portfolio = models.CharField(max_length=200)
    men_coord_img = models.FileField('File', upload_to='coordinators')
    men_coord_name = models.CharField(max_length=200)
    men_coord_course = models.CharField(max_length=200)
    men_coord_hostel = models.CharField(max_length=200)

newwine/forms.py
from django import forms
from .models import RegisteredMembers


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = RegisteredMembers
        fields = ['first_name', 'surname', 'email', 'gender', 'date_of_birth', 'course', 'year',
                  'hall_or_hostel', 'room', 'department', 'covenant_family', 'home_temple', 'phone']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'surname': forms.TextInput(attrs={'placeholder': 'Surname'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
            'gender': forms.TextInput(attrs={'placeholder': 'Gender'}),
            'date_of_birth': forms.TextInput(attrs={'placeholder': 'Date of birth (mm/dd/yyyy)'}),
            'course': forms.TextInput(attrs={'placeholder': 'Course'}),
            'year': forms.TextInput(attrs={'placeholder': 'Year'}),
            'hall_or_hostel': forms.TextInput(attrs={'placeholder': 'Hall or Hostel'}),
            'room': forms.TextInput(attrs={'placeholder': 'Room'}),
            'department': forms.TextInput(attrs={'placeholder': 'Church Department'}),
            'covenant_family': forms.TextInput(attrs={'placeholder': 'Covenant Family'}),
            'home_temple': forms.TextInput(attrs={'placeholder': 'Home Temple'}),
            'phone': forms.TextInput(attrs={'placeholder': 'Phone Number'}),
        }

newwine/templates/newwine/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="ICGC Newwine Web Team">
    <meta name="description" content="ICGC CAMPUS MINISTRY, NEWWINE WEBSITE">
    <meta name="keywords" content="ICGC, NEWWINE, ICGC NEWWINE, ICGC CAMPUS MINISTRY">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Title{% endblock %}</title>
    {% load staticfiles %}
    <link rel="icon" type="image/png" href="{% static 'newwine/static/img/icgc/logo.png' %}" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'newwine/static/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'newwine/static/css/animate.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'newwine/static/css/style2.css' %}" />
    <style>
      .btn.focus, .btn:focus, .btn:hover {
          color: #fff !important; 
          text-decoration: none;
      }

      
         
    @media (max-width: 1200px) {
        .navbar {
            overflow-y: auto;
            max-height: 85vh;
        }
        .navbar-header {
            float: none;
        }
        .navbar-left,.navbar-right {
            float: none !important;
        }
        .navbar-toggle {
            display: block;
            margin-top: 12px !important;
            border: 1px solid rgba(255, 255, 255, 0.4) !important;
            margin-right: 15px !important;
        }
        .navbar-collapse {
            border-top: 1px solid transparent;
            box-shadow: inset 0 1px 0 rgba(255,255,255,0.1);
        }
        .navbar-fixed-top {
            top: 0;
            border-width: 0 0 1px;
        }
        .navbar-collapse.collapse {
            display: none!important;
        }
        .navbar-nav {
            float: none!important;
            margin-top: 7.5px;
        }
        .navbar-nav>li {
            float: none;
        }
        .navbar-nav>li>a {
            padding-top: 10px;
            padding-bottom: 10px;
        }
        .collapse.in{
            display:block !important;
        }
    }

    collapse, .navbar-fixed-top .navbar-collapse {
      max-height: none;
    }

      @media (max-width: 1200px){
      .navbar-nav .open .dropdown-menu {
          position: static;
          float: none;
          width: auto;
          margin-top: 0;
          background-color: transparent;
          border: 0;
          -webkit-box-shadow: none;
          box-shadow: none;
      }
    }

    .navbar-fixed-bottom .navbar-collapse,.navbar-fixed-top .navbar-collapse{
        max-height: none;
    }
    .navbar>.container .navbar-brand, .navbar>.container-fluid .navbar-brand {
        margin-left: 0px !important;
    }

 

    .container-fluid>.navbar-collapse, .container-fluid>.navbar-header, .container>.navbar-collapse, .container>.navbar-header {
        margin-right: 0px !important;
        margin-left: 0px !important;
    }
    </style>
    {% block css %}
    {% endblock %}
</head>



{% block body %}


{% endblock %}

{% block footer %}
<!-- footer -->
{% url 'newwine:images' as images %}
<div class="footer" {% if request.path == images %} style="margin-top: 50px;" {% endif %}>

<div id="back-to-top"></div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
          <div class="contact">
            <h4 class="contact-head">CONTACT US</h4>
            <p class="email">Email us on <a class="email-link" href="mailto:knust.campusministry@centralgospel.com">knust.campusministry@centralgospel.com</a></p>
            <p class="phone">Phone no. 0558218325</p>
          </div>
      </div>
    <div class="col-xs-12 col-sm-6">
          <div class="social">
              <a target="_blank" href="https://web.facebook.com/icgcknust/?ref=br_rs"><i class="fab fa-facebook-f footer-social facebook"></i></a>
              <a target="_blank" href="https://www.instagram.com/icgcknust/"><i class="fab fa-instagram footer-social instagram"></i></a>
      </div>
      <!-- @icgcknustcm -->
            <div class="creator-info">
              <div class="creator">Made by <span class="">ICGC WEB TEAM</span></div>
              <div class="copyright">Copyright &copy; 2019. All rights reserved</div>
            </div>
        </div>
  </div>
</div>

<div class="footer-logo">
  <a href="#"><span></span></a>
</div>  
</div>
</div>
<!-- footer end -->
</div>
</body>
{% endblock %}



<script type="text/javascript" src="{% static 'newwine/static/js/jquery-1.11.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'newwine/static/js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'newwine/static/js/jquery.easing.min.js' %}"></script>
<script type="text/javascript" src="{% static 'newwine/static/js/wow.min.js' %}"></script>
<script type="text/javascript" src="{% static 'newwine/static/js/sb.js' %}"></script>
<script type="text/javascript">
    $(function(){
        var navMain = $(".navbar-collapse");
        navMain.on("click", "a:not([data-toggle])", null, function () {
            navMain.collapse('hide');
        });
    });
</script>

{% block js %}{% endblock %}

</html>

newwine/templates/newwine/registration_error.html
{% extends 'newwine/base.html' %}
{% block title %}Registration | New Wine{% endblock %}

{% load staticfiles %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'newwine/static/css/upcoming.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'newwine/static/css/style.css' %}" />
{% endblock %}


{% block body %}
<body>
{% include 'newwine/static-navbar.html' %}


<div style="margin-top: 100px;" class="container">
	<div class="row">
		<div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
			<div class="message">
				<p style="font-size: 20px; margin-bottom: 50px; margin-top: 30px; text-align: center;"><i class='fa fa-4x fa-frown-o'></i></p>
				<p style="font-size: 20px; margin-bottom: 50px;">
					There was an error in your data. Please go back and fill the form again. Thank You for your cooperation
				</p>
				<a style="color: rgba(0,0,0,1.00); font-size: 25px; margin-bottom: 150px; text-align: center;" href="{% url 'newwine:registration' %}">Back</a>
			</div>
		</div>
	</div>	
</div>
</body>

{% endblock %}

{% block footer %}
{% endblock%}

{% block js %}
<script type="text/javascript" src="{% static 'newwine/static/js/main.js' %}"></script>
{% endblock %}

newwine/templates/newwine/static-navbar.html
{% load staticfiles %}

{% block css %}

<link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'newwine/static/css/mod.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'newwine/static/css/style.css' %}" />
<style>
  .dropdown-menu > li > a {
        color: rgb(255, 255, 255);
        transition: all 0.3s ease-in-out;
        -webkit-transition: all 0.3s ease-in-out;
        -o-transition: all 0.3s ease-in-out;
        -moz-transition: all 0.3s ease-in-out;
    }

    .navbar-inverse {
        background-color: #222;
        border-color: transparent;
    }

@media (max-width: 1200px) {
    .navbar {
        overflow-y: auto;
        max-height: 85vh;
    }
    .navbar-header {
        float: none;
    }
    .navbar-left,.navbar-right {
        float: none !important;
    }
    .navbar-toggle {
        display: block;
        margin-right: 30px;
    }
    .navbar-collapse {
        border-top: 1px solid transparent;
        box-shadow: inset 0 1px 0 rgba(255,255,255,0.1);
    }
    .navbar-fixed-top {
        top: 0;
        border-width: 0 0 1px;
    }
    .navbar-collapse.collapse {
        display: none!important;
    }
    .navbar-nav {
        float: none!important;
        margin-top: 7.5px;
    }
    .navbar-nav>li {
        float: none;
    }
    .navbar-nav>li>a {
        padding-top: 10px;
        padding-bottom: 10px;
    }
    .collapse.in{
        display:block !important;
    }
}
</style>

{% endblock %}

<nav id="mainNav" class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top"><img src="{% static 'newwine/static/img/icgc/logo.png' %}" alt="" width="65px" height="65px" /></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
             <ul class="nav navbar-nav navbar-right">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a class="page-scroll" href="{% url 'newwine:index' %}">Home</a>
                </li>
                <li>
                    <a class="page-scroll" href="{% url 'newwine:about' %}">About</a>
                </li>
                    

                <li>
                    <a class="page-scroll" href="{% url 'newwine:executives' %}">Executives</a>
                </li>
                <li class="dropdown"> 
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Departments <b class="caret"></b> </a> 
                    <ul class="dropdown-menu"> 
                    <li><a href="/department/1/">Pneuma Arts</a></li>
                    <li><a href="/department/2/">Music Department</a></li>
                    <li><a href="/department/3/">Ushering Department</a></li>
                    <li><a href="/department/4/">Welfare Department</a></li>
                    <li><a href="/department/5/">Communications Department</a></li>
                    <li><a href="/department/6/">Outreach Department</a></li>
                    <li><a href="/department/7/">Protocol Department</a></li>
                    <li><a href="/department/8/">Intercessory Department</a></li>
                    <li><a href="/department/9/">Technical Department</a></li> 
                    </ul> 
                </li>
                <li class="dropdown"> 
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Coordinators<b class="caret"></b> </a> 
                    <ul class="dropdown-menu"> 
                        <li><a href="/coordinator/1/">Deputy Financial Secretary</a></li> 
                        <li><a href="/coordinator/2/">Bible Study Coordinator</a></li>
                        <li><a href="/coordinator/3/">Transport Coordinator</a></li>
                        <li><a href="/coordinator/4/">Halls & Hostels Coordinator</a></li>
                        <li><a href="/gender-coordinators/">Gender Ministries Coordinators</a></li>
                    </ul> 
                </li>
                <li class="dropdown"> 
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Teams<b class="caret"></b> </a> 
                    <ul class="dropdown-menu"> 
                        <li><a href="/team/1/">Medical Team</a></li>
                    </ul> 
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Covenant Family <b class="caret"></b> </a> 
                    <ul class="dropdown-menu">
                    {% for item in family %}
                    <li><a href="#" data-popup-open="popup-{{ forloop.counter }}">{{ item.cov_name }}</a></li>
                    {% endfor %}
                    </ul>
                </li>
                    <li>
                        <a class="page-scroll" href="{% url 'newwine:registration' %}">Registration</a>
                    </li>
                    <li class="dropdown"> 
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Blog <b class="caret"></b> </a> 
                      <ul class="dropdown-menu"> 
                        <li><a href="{% url 'newwine:articles' %}">Articles</a></li> 
                        <li><a href="{% url 'newwine:testimonies' %}">Testimonies</a></li>
                        <li><a href="{% url 'newwine:teachings' %}">Teachings</a></li>
                        <li><a href="{% url 'newwine:outlines' %}">Bible Study Outlines</a></li>
                        <li><a href="{% url 'newwine:theme' %}">Theme of the semester</a></li>
                      </ul> 
                    </li>
                    <li class="dropdown"> 
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Media <b class="caret"></b> </a> 
                        <ul class="dropdown-menu"> 
                          <li><a href="{% url 'newwine:images' %}">Images</a></li> 
                          <li><a href="{% url 'newwine:sermons' %}">Sermons</a></li>
                          <li><a href="{% url 'newwine:videos' %}">Videos</a></li> 
                          <!-- <li><a href="{% url 'newwine:documents' %}">Books</a></li>  -->
                        </ul> 
                    </li>
                </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

{% include 'newwine/modal.html' %}